apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - env:
            - name: WEB_DOCUMENT_ROOT
              value: /app
          image: webdevops/php-nginx-dev:8.1
          name: backend
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: backend-claim0
          workingDir: /app
      restartPolicy: Always
      volumes:
        - name: backend-claim0
          persistentVolumeClaim:
            claimName: backend-claim0
status: {}
