apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap_env.yaml
  - manifests/configmap_sql.yaml
  - manifests/cronjob.yaml
  - manifests/ingress.yaml
  - manifests/service.yaml
  - manifests/statefulset.yaml
