# Google MySQL instance ID: taskbase
# StatefulSet ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-env
#  namespace: project
data:
  MARIADB_DATABASE: taskdb
  MARIADB_TABLE: taskproject
  MARIADB_HOST: localhost
  API_HOST: taskproject-svc:8081

  