apiVersion: v1 # Includes the Service for lazyness
kind: Service
metadata:
  name: taskproject-svc
  namespace: project
  labels:
    app: tsp
spec:
  type: NodePort
  selector:
    app: tsp
  ports:
  - port: 8080
    protocol: TCP
#    targetPort: frontend-port
    name: frontend-port
  - port: 8081
    protocol: TCP
#    targetPort: backend-port
    name: backend-port
  - port: 3306
    protocol: TCP
#    targetPort: mariadb-port
    name: mariadb-port
#  - port: 8080
#    protocol: TCP
#    targetPort: dbtool-port