name: Build and Deploy to GKE

on:
  push:
    branches:
    - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: eu.gcr.io 
  GKE_CLUSTER: dwk-cluster   
  GKE_ZONE: europe-north1-b  
#  DEPLOYMENT_NAME: gke-test # TODO: update deployment name if changed in deployment.yaml or service.yml
  REPOSITORY: dwk-gke-360910
  IMAGE: dok-project

jobs:
  setup-build-publish-deploy: 
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: 'actions/checkout@v3'

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/26772408224/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'github-actions@dwk-gke-360910.iam.gserviceaccount.com'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication (https://cloud.google.com/artifact-registry/docs/docker/authentication)
    - name: Docker configuration
      run: |-
        gcloud --quiet auth configure-docker
    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    # Build the Docker images
    - name: Build backend
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/backend:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          ./backend
    - name: Build frontend
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/frontend:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          ./frontend
    - name: Build cronjob
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/cronjob:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          ./cronjob

    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/cronjob:$GITHUB_SHA"

    # Push the Docker image to Google Container Registry
    - name: Publish backend
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/backend:$GITHUB_SHA"
    - name: Publish frontend
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/frontend:$GITHUB_SHA"
    - name: Publish cronjob
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/cronjob:$GITHUB_SHA"
    - name: Pull mariadb from docker
      run: |-
        docker pull mariadb:latest
        docker tag mariadb:latest "$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/mariadb:$GITHUB_SHA"
    - name: Publish mariadb to G
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/mariadb:$GITHUB_SHA"
    - name: Pull adminer from docker
      run: |-
        docker pull adminer:latest
        docker tag adminer:latest "$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/adminer:$GITHUB_SHA"
    - name: Publish adminer to G
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/adminer:$GITHUB_SHA"

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE/BACKEND=$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/backend:$GITHUB_SHA
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE/FRONTEND=$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/frontend:$GITHUB_SHA
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE/MARIADB=$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/mariadb:$GITHUB_SHA
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE/CRONJOB=$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/cronjob:$GITHUB_SHA
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE/ADMINER=$GAR_LOCATION-docker.pkg.dev/$REPOSITORY/$IMAGE/adminer:$GITHUB_SHA

        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide